version: '3.8'

services:
  sweeper-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env.dev
    environment:
      - MODE=development
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - SQLALCHEMY_DATABASE_URI=${DATABASE_URI}  # Use the environment variable from .env.dev
    depends_on:
      - db
    volumes:
      - ./app:/app
      - media_folder:/app/media  # Mount the media folder
  db:
    image: postgres:14
    build:
      context: ./postgres
      dockerfile: postgres.Dockerfile
    container_name: db
    env_file:
      - .env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/vector_extension.sql:/docker-entrypoint-initdb.d/0-vector_extension.sql
    environment:
    - POSTGRES_NAME=sweeper
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
  
volumes:
  postgres_data:
  media_folder: